services:
  # Backend API
  - type: web
    name: hospital-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: hospital-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: hospital-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hospital-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: hospital-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: hospital-db
          property: port



databases:
  - name: hospital-db
    databaseName: hospital
    user: hospital_user
    plan: starter 