services:
  - type: web
    name: hospital-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: SECRET_KEY
        value: hospital_management_secret_key_2024_secure_and_unique
      - key: DATABASE_URL
        value: postgresql://postgres:password@localhost:5432/hospital
    healthCheckPath: /
    autoDeploy: true 