services:
  - type: web
    name: hospital-management-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run quick-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true 